image: java:8-jdk

stages:
  - build
  - test
  - deploy

before_script:
#  - echo `pwd` # debug
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x ./gradlew

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew assemble

test:
  stage: test
  script:
    - ./gradlew check
    - ./gradlew jacocoTestReport
    - cat build/jacocoHtml/index.html
  artifacts:
    reports:
      junit: build/test-results/test/TEST-*.xml

deploy:
  stage: deploy
  script:
    - ./gradlew publish
  only:
    - master

pages:
  stage: deploy
  script:
    - ./gradlew javadoc
    - cp -R build/docs/* ./public
    - "curl -X POST -F token=$TRIGGER_PAGES_TOKEN -F ref=master https://gitlab.rlp.net/api/v4/projects/2644/trigger/pipeline"
  artifacts:
    paths:
      - public
  only:
    - master
    - 16-trigger-pages-deployment-from-pipline

update_mirror:
  stage: deploy
  script:
    - echo "$SSH_IDENT_SETUP"
    - mkdir ~/.ssh 
    - ssh-keyscan -H github.com >> ~/.ssh/known_hosts
    - touch ~/.ssh/config
    - echo "$SSH_IDENT_SETUP" >> ~/.ssh/config
    - touch ~/.ssh/id_rsa_custom
    - echo "$GITHUB_SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa_custom
    - chmod 400 ~/.ssh/id_rsa_custom
    - git remote add __mirror__ git@custom:jonasohland/AsyncService.git
    - git checkout origin/master
    - git fetch __mirror__
    - git push __mirror__ HEAD:master --force
    - git remote remove __mirror__
  only:
    - master




after_script:
  - echo "End CI"